apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logapp.fullname" . }}
  labels:
    {{- include "logapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logapp.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "logapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        env:
        - name: SOMEVAR
          value: NOTHING
        - name: AWS_ACCESS_KEY_ID
          value: NOTHING
        - name: AWS_SECRET_ACCESS_KEY
          value: NOTHING
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http